packages:
  - packages/*
  - apps/*
  - docs
  - examples/*
  - "!**/test/**"

catalog:
  "@eslint/js": ^10.0.1
  "@microsoft/api-extractor": ^7.57.7
  "@tari-project/indexer-client": ^1.2.1
  "@tari-project/ootle-ts-bindings": ^1.30.0
  "@tari-project/ootle-wasm": ^0.3.0
  "@tari-project/wallet_jrpc_client": ^1.14.0
  "@types/node": ^25.5.0
  eslint: ^10.0.3
  eslint-config-prettier: ^10.1.8
  knip: ^6.0.0
  prettier: ^3.8.1
  typedoc: ^0.28.17
  typedoc-plugin-markdown: ^4.10.0
  typescript: ^5.9.3
  typescript-eslint: ^8.57.0
  unplugin-dts: ^1.0.0-beta.6
  vite: ^8.0.1
  vite-plugin-top-level-await: ^1.6.0
  vite-plugin-wasm: ^3.6.0
  vitest: ^4.1.0

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
