packages:
  - packages/*
  - apps/*
  - docusaurus/*
  - examples/*
  - "!**/test/**"

catalog:
  typescript: ^5.0.4
  vitest: ^3.0.4
  vite: ^6.1.0
  "@types/node": ^22.13.1
  "@tari-project/typescript-bindings": ">=1.17.2"
  "@tari-project/wallet_jrpc_client": ^1.9.2
  "@metamask/providers": ^18.2.0
  "@walletconnect/universal-provider": 2.21.3 
  "@reown/appkit": "1.7.15"

onlyBuiltDependencies:
  - "@moonrepo/cli"
  - core-js
  - core-js-pure
  - esbuild
