// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialWithdrawProof } from "./ConfidentialWithdrawProof";

export interface ConfidentialClaim {
  publicKey: string;
  outputAddress: string;
  rangeProof: Array<number>;
  proofOfKnowledge: string;
  withdrawProof?: ConfidentialWithdrawProof;
}
