// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { SubstateId } from "@tariproject/typescript-bindings";

export interface VersionedSubstateId {
  substateId: SubstateId;
  version: number;
}
